// === Upgrades Data — Upgrade definitions, shadow theme, helpers ===
'use strict';

import { gameMode, getUpgradeCount } from './state.js';

// --- Upgrades Definition ---
export const UPGRADES = [
  {
    id: 'spark',
    name: 'Spark',
    desc: 'Rub, and the glow is born',
    baseCost: 50,
    costMultiplier: 1.4,
    type: 'passive',
    value: 1,
    maxCount: 50,
    unlockAt: 0,
  },
  {
    id: 'firefly',
    name: 'Firefly',
    desc: 'Blinks in the dark',
    baseCost: 150,
    costMultiplier: 1.7,
    type: 'burst',
    value: 1,
    maxCount: 25,
    unlockAt: 80,
  },
  {
    id: 'candle',
    name: 'Candle',
    desc: 'It melts so others can see',
    baseCost: 400,
    costMultiplier: 1.5,
    type: 'passive',
    value: 5,
    maxCount: 30,
    unlockAt: 250,
  },
  {
    id: 'prism',
    name: 'Prism',
    desc: 'One ray in, seven out',
    baseCost: 1000,
    costMultiplier: 1.9,
    type: 'click',
    value: 3,
    maxCount: 20,
    unlockAt: 600,
  },
  {
    id: 'lantern',
    name: 'Lantern',
    desc: 'The caged flame travels far',
    baseCost: 3000,
    costMultiplier: 1.5,
    type: 'passive',
    value: 20,
    maxCount: 25,
    unlockAt: 2000,
  },
  {
    id: 'lightning',
    name: 'Lightning',
    desc: 'Strikes and illuminates',
    baseCost: 8000,
    costMultiplier: 2.0,
    type: 'click',
    value: 10,
    maxCount: 15,
    unlockAt: 5000,
  },
  {
    id: 'lighthouse',
    name: 'Lighthouse',
    desc: 'Turns endlessly for the lost',
    baseCost: 15000,
    costMultiplier: 1.6,
    type: 'passive',
    value: 80,
    maxCount: 20,
    unlockAt: 10000,
  },
  {
    id: 'aurora',
    name: 'Aurora',
    desc: 'Solar wind touches the sky',
    baseCost: 40000,
    costMultiplier: 1.6,
    type: 'passive',
    value: 250,
    maxCount: 15,
    unlockAt: 25000,
  },
  {
    id: 'star',
    name: 'Star',
    desc: 'Four billion years of fusion',
    baseCost: 100000,
    costMultiplier: 1.7,
    type: 'passive',
    value: 800,
    maxCount: 10,
    unlockAt: 60000,
  },
  {
    id: 'supernova',
    name: 'Supernova',
    desc: 'The star dies in a scream of light',
    baseCost: 300000,
    costMultiplier: 1.65,
    type: 'passive',
    value: 2500,
    maxCount: 10,
    unlockAt: 180000,
  },
  {
    id: 'pulsar',
    name: 'Pulsar',
    desc: 'A heartbeat in the void',
    baseCost: 800000,
    costMultiplier: 2.0,
    type: 'click',
    value: 35,
    maxCount: 12,
    unlockAt: 450000,
  },
  {
    id: 'nebula',
    name: 'Nebula',
    desc: 'The cradle of unborn suns',
    baseCost: 2000000,
    costMultiplier: 1.6,
    type: 'passive',
    value: 8000,
    maxCount: 10,
    unlockAt: 1200000,
  },
  {
    id: 'comet',
    name: 'Comet',
    desc: 'A trail of ice and fire',
    baseCost: 5000000,
    costMultiplier: 1.8,
    type: 'burst',
    value: 2,
    maxCount: 20,
    unlockAt: 3000000,
  },
  {
    id: 'quasar',
    name: 'Quasar',
    desc: 'Brighter than a billion suns',
    baseCost: 15000000,
    costMultiplier: 1.65,
    type: 'passive',
    value: 30000,
    maxCount: 8,
    unlockAt: 8000000,
  },
  {
    id: 'plasma',
    name: 'Plasma',
    desc: 'The fourth state of matter',
    baseCost: 40000000,
    costMultiplier: 2.0,
    type: 'click',
    value: 120,
    maxCount: 10,
    unlockAt: 20000000,
  },
  {
    id: 'constellation',
    name: 'Constellation',
    desc: 'Stories written in the sky',
    baseCost: 100000000,
    costMultiplier: 1.6,
    type: 'passive',
    value: 100000,
    maxCount: 8,
    unlockAt: 55000000,
  },
  {
    id: 'galaxy',
    name: 'Galaxy',
    desc: 'A hundred billion stars dance',
    baseCost: 300000000,
    costMultiplier: 1.65,
    type: 'passive',
    value: 350000,
    maxCount: 6,
    unlockAt: 150000000,
  },
  {
    id: 'whitehole',
    name: 'White Hole',
    desc: 'What was swallowed is returned',
    baseCost: 1000000000,
    costMultiplier: 1.7,
    type: 'passive',
    value: 1200000,
    maxCount: 6,
    unlockAt: 500000000,
  },
  {
    id: 'darkmatter',
    name: 'Dark Matter',
    desc: 'Invisible, it sculpts the universe',
    baseCost: 3000000000,
    costMultiplier: 1.7,
    type: 'passive',
    value: 4000000,
    maxCount: 5,
    unlockAt: 1500000000,
  },
  {
    id: 'bigbang',
    name: 'Big Bang',
    desc: 'Let there be light',
    baseCost: 10000000000,
    costMultiplier: 1.75,
    type: 'passive',
    value: 15000000,
    maxCount: 5,
    unlockAt: 5000000000,
  },
  {
    id: 'cosmiclight',
    name: 'Cosmic Light',
    desc: 'The echo of the first instant',
    baseCost: 30000000000,
    costMultiplier: 1.8,
    type: 'passive',
    value: 50000000,
    maxCount: 4,
    unlockAt: 15000000000,
  },
  {
    id: 'multiverse',
    name: 'Multiverse',
    desc: 'Every choice, a new sun',
    baseCost: 100000000000,
    costMultiplier: 1.85,
    type: 'passive',
    value: 200000000,
    maxCount: 3,
    unlockAt: 50000000000,
  },
  {
    id: 'eternity',
    name: 'Eternity',
    desc: 'Time is nothing but a glimmer',
    baseCost: 400000000000,
    costMultiplier: 1.9,
    type: 'passive',
    value: 800000000,
    maxCount: 3,
    unlockAt: 180000000000,
  },
  {
    id: 'sun',
    name: 'Sun',
    desc: '?',
    baseCost: 1000000000000,
    costMultiplier: 1,
    type: 'victory',
    value: 0,
    maxCount: 1,
    unlockAt: 500000000000,
  },
];

// --- Shadow-themed names/descriptions for Off mode ---
export const SHADOW_THEME = {
  spark:         { name: 'Whisper',           desc: 'The first sound fading out' },
  firefly:       { name: 'Ephemeral',         desc: 'Exists only to vanish' },
  candle:        { name: 'Soot',              desc: 'What remains when the flame dies' },
  prism:         { name: 'Onyx',              desc: 'The stone that swallows light' },
  lantern:       { name: 'Ember',             desc: 'The last breath of fire' },
  lightning:     { name: 'Fissure',           desc: 'Reality cracks open' },
  lighthouse:    { name: 'Siren',             desc: 'Lures toward the depths' },
  aurora:        { name: 'Twilight',          desc: 'The sky closes shut' },
  star:          { name: 'Cinder',            desc: 'Dust of what once was' },
  supernova:     { name: 'Singularity',       desc: 'The point of no return' },
  pulsar:        { name: 'Vortex',            desc: 'A bottomless whirlpool' },
  nebula:        { name: 'Miasma',            desc: 'A fog that devours' },
  comet:         { name: 'Specter',           desc: 'The echo of a dead light' },
  quasar:        { name: 'Abyss',             desc: 'Stare too long, it stares back' },
  plasma:        { name: 'Entropy',           desc: 'Absolute disorder' },
  constellation: { name: 'Oblivion',          desc: 'Memories dissolve' },
  galaxy:        { name: 'Maelstrom',         desc: 'The final whirlpool' },
  whitehole:     { name: 'Horizon',           desc: 'Beyond it, nothing returns' },
  darkmatter:    { name: 'Void',              desc: 'The very absence of absence' },
  bigbang:       { name: 'Big Crunch',        desc: 'The universe folds upon itself' },
  cosmiclight:   { name: 'Cosmic Silence',    desc: 'The last echo fades' },
  multiverse:    { name: 'Dissolution',       desc: 'Matter returns to the void' },
  eternity:      { name: 'Extinction',        desc: 'Time ceases to flow' },
  sun:           { name: 'Eclipse',           desc: '?' },
};

// Helper to get display name/desc based on current mode
export function getUpgradeName(up) {
  if (gameMode === 'off' && SHADOW_THEME[up.id]) return SHADOW_THEME[up.id].name;
  return up.name;
}

export function getUpgradeDesc(up) {
  if (gameMode === 'off' && SHADOW_THEME[up.id]) return SHADOW_THEME[up.id].desc;
  return up.desc;
}

// --- Upgrade cost calculation ---
export function getUpgradeCost(upgrade) {
  const count = getUpgradeCount(upgrade.id);
  return Math.floor(upgrade.baseCost * Math.pow(upgrade.costMultiplier, count));
}
